name: Simple Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  log-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log a message
        run: echo "✅ Hello from GitHub Actions! This is a test log."
